// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTf27YE6rqjB9JLGXCvV38ccLhgpCLSy4',
    appId: '1:877178482395:web:66e7ea58c1f64cdcc6e6fe',
    messagingSenderId: '877178482395',
    projectId: 'project-2-6b695',
    authDomain: 'project-2-6b695.firebaseapp.com',
    storageBucket: 'project-2-6b695.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKSEuzib8-9FQmbOD5J3DsYhTohmrCj8',
    appId: '1:877178482395:android:2d9d318e923116a8c6e6fe',
    messagingSenderId: '877178482395',
    projectId: 'project-2-6b695',
    storageBucket: 'project-2-6b695.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzHL2eA1EoBUihU9-7LVmje4tqrdqWedI',
    appId: '1:877178482395:ios:dae46e61458e113bc6e6fe',
    messagingSenderId: '877178482395',
    projectId: 'project-2-6b695',
    storageBucket: 'project-2-6b695.firebasestorage.app',
    iosBundleId: 'com.example.mobileInventory',
  );
}
